Albania
Algeria
American Samoa
Andorra
Angola
Anguilla
Antigua
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Barbuda
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
Bonaire
Botswana
Brazil
British Virgin isl.
Brunei
Bulgaria
Burundi
Cambodia
Cameroon
Canada
Cape Verde
Cayman Islands
Central African Rep.
Chad
Channel Islands
Chile
China
Colombia
Congo
Cook Islands
Costa Rica
Croatia
Curacao
Cyprus
Czech Republic
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Faeroe Islands
Fiji
Finland
France
French Guiana
French Polynesia
Gabon
Gambia
Georgia
Germany
Ghana
Gibraltar
Great Britain
Greece
Greenland
Grenada
Guadeloupe
Guam
Guatemala
Guinea
Guinea Bissau
Guyana
Haiti
Honduras
Hong Kong
Hungary
Iceland
India
Indonesia
Irak
Iran
Ireland
Ireland, Northern
Israel
Italy
Ivory Coast
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kuwait
Kyrgyzstan
Latvia
Lebanon
Liberia
Liechtenstein
Lithuania
Luxembourg
Macau
Macedonia
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Martinique
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montserrat
Morocco
Mozambique
Myanmar/Burma
Namibia
Nepal
Netherlands
Netherlands Antilles
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Reunion
Rwanda
Saba
Saipan
Saudi Arabia
Scotland
Senegal
Seychelles
Sierra Leone
Singapore
Slovak Republic
Slovenia
South Africa
South Korea
Spain
Sri Lanka
Sudan
Suriname
Swaziland
Sweden
Switzerland
Syria
Taiwan
Tanzania
Thailand
Togo
Trinidad-Tobago
Tunisia
Turkey
Turkmenistan
United Arab Emirates
U.S. Virgin Islands
U.S.A.
Uganda
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Vatican City
Venezuela
Vietnam
Wales
Yemen
Zaire
Zambia
Zimbabwe